- name: "#cars" # ðŸš˜
  slug: cars
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: kind="video"&&channel.tags?~"4nhdxhpy2ytu5ms"&&channel.category="d6rzqzfpcfpvh7w"
