- name: "#cars" # ðŸš˜
  slug: cars
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="cars"&&channel.category.code="ent"
