- name: "#chess"
  slug: chess
  width: wide
  columns:

    - size: full
      widgets:

    - size: full
      widgets:

        - <<: *backube-xml
          title: "Videos"
          options:
            collapse-after-rows: 8
          parameters:
            channel:
              - UCE1u2aEeOZn22nsochlieFQ #@DinaBelenkaya
              - UCAn8NrZ-J4CRfwodajqFYoQ # BotezLive
              - UCOVfq3NNYjlYCz1iou69FwQ # AnnaCramling
              - UCX1aKS73OTYKAD-D5dno73w # akaNemsko
              - UCQHX6ViZmPsWiYSFAyS0a3Q # GothamChess
