- name: "Crime" # ğŸ’€
  slug: crime
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        filter: channel.tags.name?="crime"&&channel.category.code="ent"

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover
              subreddit: Crime

            - <<: *reddit-cover
              subreddit: acab+Bad_Cop_No_Donut

            - <<: *reddit-cover
              subreddit: WithoutATrace
