- name: "Crime" # ðŸ’€
  slug: crime
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 2
          widgets:

            - <<: *reddit-cover
              subreddit: Crime

            - <<: *reddit-cover
              subreddit: WithoutATrace

    - size: full
      widgets:

        - <<: *backube-xml
          title: "Videos"
          options:
            collapse-after-rows: 6
          parameters:
            channel:
              - UCJWKjrrUh2KL1d3zXQW79cQ # ExploreWithUs
              - UCYwVxWpjeKFWwu8TML-Te9A # JCS - Criminal Psychology
              - UCFXad0mx4WxY1fXdbvtg0CQ # Fascinating Horror
              - UCCKwTsUwBvMDNlhxf0evJag # deathdoor4687
              - UCFkFUrV28yy4kpg9b6LNhuQ #@TrueCrimeCentral
              - UC0JJtK3m8pwy6rVgnBz47Rw #@rottenmangopod
              - UCAa4yNsAyP-O5j-qNSpVQ_g #@AmerikaliAynasiz
