- name: "Daily"
  slug: daily
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Social
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="social"

        - <<: *backube-latest
          title: Pranks
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="pranks"

        - <<: *backube-latest
          title: Interviews
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="interviews"

        - <<: *backube-latest
          title: day in life
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="day in life"

    - size: full
      widgets:

        - <<: *backube-latest
          title: Travel
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="travel"

        - <<: *backube-latest
          title: Outdoor
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="outdoor"

        - <<: *backube-latest
          title: Camping
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="camping"

        - <<: *backube-latest
          title: Chess
          options:
            collapse-after-rows: 1
            min-card-width-px: 240
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="chess"
