- name: "Docs" # ğŸ“½ï¸
  slug: documentaries
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        filter: channel.category.code!="ggwp"&&(channel.tags.name?="documentaries"||channel.tags.name?="stories")

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover-top-week
              subreddit: documentaries

            - <<: *reddit-cover-top-week
              subreddit: 911archive
