- name: "Docs" # ğŸ“½ï¸
  slug: documentaries
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category!="5doguxzor0eekxd"&&(channel.tags?~"d10itz88jw1gdj4"||channel.tags?~"erfn5fv3moup4gh")

  columns:

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: r/documentaries
          options:
            subreddit: documentaries
            min-column-width: 420
