- name: "Docs" # ğŸ“½ï¸
  slug: documentaries
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 2
          widgets:

            - <<: *reddit-cover-top-week
              subreddit: documentaries

            - <<: *reddit-cover-top-week
              subreddit: 911archive

    - size: full
      widgets:

        - <<: *backube-latest
          options:
            collapse-after-rows: 6
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.category.code!="ggwp"&&(channel.tags.name?="documentaries"||channel.tags.name?="stories")
