- name: "Popcorn" # ğŸ¤–
  slug: entertainment
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 2
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: kind="video"&&channel.category="d6rzqzfpcfpvh7w"&&channel.tags!~"8eskm8v85t341ty"&&channel.language!="c3u5dojqveecd62"

        - <<: *xeddit-waterfall
          title: r/popular
          options:
            subreddit: funny+Showerthoughts+explainlikeimfive+mildlyinteresting+tifu+UpliftingNews+OldSchoolCool+bestof+interestingasfuck+confession+OutOfTheLoop+HistoryPorn+MurderedByWords+youseeingthisshit+YouShouldKnow+KidsAreFuckingStupid+entertainment+niceguys+AbandonedPorn+CatastrophicFailure+AmItheAsshole
            limit: 50
