- name: "Finance" # ğŸª™
  slug: finance
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: channel.tags.name?="economy"||channel.tags.name?="money"

  columns:

    - size: small
      widgets:

        - <<: *markets-base
          markets:
            - symbol: TRY=X
            - symbol: EURTRY=X

        - <<: *markets-base
          title: Stocks
          markets:
            - symbol: TSLA
            - symbol: NVDA
            - symbol: AAPL
            - symbol: AMZN
            - symbol: INTC
            - symbol: AMD

        - <<: *markets-base
          title: Crypto
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum
            - symbol: LTC-USD
              name: Litecoin
            - symbol: DOGE-USD
              name: Dogecoin
            - symbol: XLM-USD
              name: Stellar
            #- symbol: XRP-USD
            #  name: XRP
            - symbol: SOL-USD
              name: Solana
            #- symbol: TRX-USD
            #  name: TRON

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: economy+finance
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: economy+finance

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: CryptoCurrency+Bitcoin
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: CryptoCurrency+Bitcoin

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: investing+wallstreetbets
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: investing+wallstreetbets
