- name: "Finance" # ğŸª™
  slug: finance
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.tags?~"3tstctouarex5k8"||channel.tags?~"94vozacbowjpuqx"

  columns:

    - size: small
      widgets:

        - <<: *markets-base
          markets:
            - symbol: TRY=X
            - symbol: EURTRY=X

        - <<: *markets-base
          title: Stocks
          markets:
            - symbol: TSLA
            - symbol: NVDA
            - symbol: AAPL
            - symbol: AMZN
            - symbol: INTC
            - symbol: AMD

        - <<: *markets-base
          title: Crypto
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum
            - symbol: LTC-USD
              name: Litecoin
            - symbol: XMR-USD
              name: Monero
            - symbol: DOGE-USD
              name: Dogecoin
            - symbol: XLM-USD
              name: Stellar
            - symbol: XRP-USD
              name: XRP
            - symbol: SOL-USD
              name: Solana
            - symbol: TRX-USD
              name: TRON

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: r/ economy & finance & investing & crypto currency
          options:
            subreddit: economy+finance+investing+wallstreetbets+CryptoCurrency+Bitcoin+CryptoMarkets+Monero
            limit: 50
