- name: "Hardware" # ğŸ¤–
  slug: hardware
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="59dtmnmo4sesehs"

  columns:

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: r/ hardware & gadgets & tech support
          options:
            subreddit: hardware+gadgets+LinusTechTips+techsupport+windows
            limit: 50
