- name: "Health" # ğŸ§« ğŸ¦ 
  slug: health
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover
              subreddit: Health
              collapse-after: 10

            - <<: *reddit-cover
              subreddit: psychology
              show-flairs: true
              collapse-after: 10

            - <<: *reddit-cover
              subreddit: Coronavirus
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/Health Top This Week
              subreddit: Health
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/psychology Top This Week
              subreddit: psychology
              collapse-after: 10
