- name: "Health" # ğŸ§« ğŸ¦ 
  slug: health
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: Health
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: Health

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: psychology
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: psychology

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: Coronavirus
                  show-flairs: true

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: Coronavirus
