- name: "Home"
  slug: home
  width: wide
  columns:

    - size: small
      widgets:

        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/New_York
              label: New York

        # - type: calendar
        #   first-day-of-week: monday

        - type: weather
          units: metric
          hour-format: 12h
          location: Bah√ßelievler

        - <<: *markets-base
          markets:
            - symbol: TRY=X
            - symbol: EURTRY=X
            - symbol: BTC-USD

        - type: custom-api
          title: Random Fact
          cache: 3h
          url: https://uselessfacts.jsph.pl/api/v2/facts/random
          template: |
            <p class="size-h4 color-paragraph">{{ .JSON.String "text" }}</p>

    - size: full
      widgets:

        - type: search
          search-engine: google
          new-tab: true
          autofocus: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/search?q={QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Steam
              shortcut: "!s"
              url: https://store.steampowered.com/search/?term={QUERY}
            - title: Amazon
              shortcut: "!a"
              url: https://www.amazon.com.tr/s?k={QUERY}
            - title: Github
              shortcut: "!g"
              url: https://github.com/search?q={QUERY}&type=repositories
            - title: Docker
              shortcut: "!d"
              url: https://hub.docker.com/search?q={QUERY}

        - <<: *docker-containers


    - size: small
      widgets:

        - type: server-stats
          servers:
            - type: local
              name: Services

        - type: dns-stats
          service: adguard
          hide-graph: true
          hide-top-domains: true
          url: ${ADGUARD_URL}
          username: ${ADGUARD_USERNAME}
          password: ${ADGUARD_PASSWORD}

        - type: bookmarks
          groups:
            - title: Local Network
              color: 31 100 71
              <<: *links-local
            - title: Privacy
              color: 10 70 50
              links:
                - title: Browser Leaks
                  url: https://browserleaks.com/ip
                - title: 1.1.1.1 Debug
                  url: https://one.one.one.one/help
            - links:
                - title: Speed Test
                  url: https://speed.cloudflare.com
                - title: Windscribe Wireguard
                  url: https://windscribe.com/getconfig/wireguard
                - title: Configuration
                  url: https://github.com/glanceapp/glance/blob/main/docs/configuration.md#configuration
