- name: "Live" # ğŸ”´
  slug: live
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: "Videos"
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind!="short"&&channel.tags?~"8eskm8v85t341ty"&&channel.tags!~"gmi87of1hdn9rym"

  columns:

    - size: small
      widgets:

        - type: twitch-channels
          channels: ["asmongold","zackrawrr","robcdee","EsfandTV","emiru","bonnie","kitboga","ej_sa","CriticalRole","ariathome","sweet_anita","agendafreetv"]
          collapse-after: 3

        - <<: *kick-channels
          title: Kick Following
          parameters:
            slug:
              - asmongold

        - <<: *twitch-category
          title: Twitch Just Chatting [EN, TR]
          options:
            collapse-after-rows: 3
          body:
            query: |
              query {
                game(id: "509658") {
                  streams(first: 4, options: { languages: ["EN", "TR"]}) {
                    edges {
                      node {
                        id
                        createdAt
                        previewImageURL(width: 440, height: 248)
                        type
                        viewersCount
                        broadcaster {
                          login
                          displayName
                          profileImageURL(width: 300)
                          broadcastSettings {
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }

        - <<: *kick-category
          title: Kick Just Chatting [EN]
          options:
            collapse-after-rows: 3
          parameters:
            category: 5
            limit: 4
            language: en

        - <<: *twitch-clips
          title: Popular Clips - Week
          options:
            collapse-after-rows: 2
          body:
            query: |
              query {
                game(name: "Just Chatting") {
                  clips(first: 30, criteria: { languages: [], period: LAST_WEEK }) {
                    edges {
                      node {
                        url
                        title
                        durationSeconds
                        createdAt
                        thumbnailURL(width: 440, height: 248)
                        viewCount
                        game {
                          displayName
                        }
                        curator {
                          login
                          displayName
                          profileImageURL(width: 50)
                        }
                        broadcaster {
                          login
                          displayName
                          profileImageURL(width: 50)
                        }
                      }
                    }
                  }
                }
              }

        - type: bookmarks
          groups:
            - links:
                - title: Rumble
                  icon: auto-invert ${ICONS_URL}/custom/rumble.svg
                  url: https://rumble.com
                - title: Social Blade
                  icon: auto-invert ${ICONS_URL}/custom/socialblade.svg
                  url: https://socialblade.com/
            - links:
                - title: x/yeet
                  url: https://x.com/Awk20000
                - title: Streams Charts
                  url: https://streamscharts.com/overview
                - title: Stream Bans
                  url: https://streamerbans.com
                - title: Twitch Tracker
                  url: https://twitchtracker.com
                - title: Naver's CHZZK
                  url: https://chzzk.naver.com

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: r/LivestreamFail
          options:
            subreddit: LivestreamFail+Asmongold+youtubedrama
