- name: "Movies" # ğŸ¿
  slug: movies
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.tags?~"ko8e0zywbttpfa6"

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/movies/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search on r/movies
          bangs:
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/post-search?q={QUERY}+subreddit%3Amovies&sort=hot&view=compact
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query={QUERY}
            - title: Bingeflix
              shortcut: "!b"
              url: https://bingeflix.tv/search?tab=movies-tv&q={QUERY}
            - title: TÃ¼rkÃ§e AltyazÄ±
              shortcut: "!t"
              url: https://turkcealtyazi.org/find.php?cat=sub&find={QUERY}
            - title: Open Subtitles
              shortcut: "!o"
              url: https://www.opensubtitles.org/en/search2/moviename-{QUERY}/sublanguageid-tur,eng


        - type: bookmarks
          css-class: page-movies
          groups:
            - links:
                - title: Metacritic Movies
                  url: https://www.metacritic.com/movie
                - title: Letterboxd Reviews
                  url: https://letterboxd.com/reviews/popular/this/week
            - title: IMDb
              color: 47 92 53
              links:
                - title: Top Box Office (US)
                  url: https://www.imdb.com/chart/boxoffice
                - title: Top 250 Movies
                  url: https://www.imdb.com/chart/top
            - title: The Movie Database (TMDB)
              color: 193 99 45
              links:
                - title: Popular Movies
                  url: https://www.themoviedb.org/movie
                - title: Upcoming Movies
                  url: https://www.themoviedb.org/movie/upcoming
            - <<: *links-subtitles
            - links:
                - title: Viki
                  url: https://www.viki.com
                - title: Prime Video
                  url: https://www.primevideo.com
            - links:
                - title: Megathread
                  url: ${REDDIT_URL}/r/Piracy/wiki/megathread/movies_and_tv#wiki_.1F4D1_.279C_streaming

        - <<: *jellyfin-movies-list
          options:
            collapse-after: 10

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: r/ movies & Cinema & Box Office
          options:
            subreddit: movies+Cinema+BoxOffice+MovieSuggestions+TrueFilm+Filmmakers+MovieDetails+Oscars
            limit: 50
