- name: "Movies" # üçø
  slug: movies
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/movies/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search on r/movies
          bangs:
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/post-search?q={QUERY}+subreddit%3Amovies&sort=hot&view=compact
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query={QUERY}
            - title: Bingeflix
              shortcut: "!b"
              url: https://bingeflix.tv/search?tab=movies-tv&q={QUERY}
            - title: T√ºrk√ße Altyazƒ±
              shortcut: "!t"
              url: https://turkcealtyazi.org/find.php?cat=sub&find={QUERY}
            - title: Open Subtitles
              shortcut: "!o"
              url: https://www.opensubtitles.org/en/search2/moviename-{QUERY}/sublanguageid-tur,eng


        - type: bookmarks
          css-class: page-movies
          groups:
            - links:
                - title: Metacritic Movies
                  url: https://www.metacritic.com/movie
                - title: Letterboxd Reviews
                  url: https://letterboxd.com/reviews/popular/this/week
            - title: IMDb
              color: 47 92 53
              links:
                - title: Top Box Office (US)
                  url: https://www.imdb.com/chart/boxoffice
                - title: Top 250 Movies
                  url: https://www.imdb.com/chart/top
            - title: The Movie Database (TMDB)
              color: 193 99 45
              links:
                - title: Popular Movies
                  url: https://www.themoviedb.org/movie
                - title: Upcoming Movies
                  url: https://www.themoviedb.org/movie/upcoming
            - <<: *links-subtitles
            - links:
                - title: Viki
                  url: https://www.viki.com
                - title: Prime Video
                  url: https://www.primevideo.com
            - links:
                - title: Megathread
                  url: ${REDDIT_URL}/r/Piracy/wiki/megathread/movies_and_tv#wiki_.1F4D1_.279C_streaming

        - <<: *jellyfin-movies-list
          options:
            collapse-after: 10

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: split-column
              max-columns: 1
              widgets:

                - type: group
                  widgets:

                    - <<: *reddit-cover
                      subreddit: movies
                      show-flairs: true
                      collapse-after: *widget-half-collapse-after

                    - <<: *reddit-cover-top-week
                      title: Top This Week
                      subreddit: movies
                      collapse-after: *widget-half-collapse-after

                - <<: *reddit-cover
                  subreddit: movies
                  title: Trailers
                  search: flair:trailer
                  sort-by: new
                  collapse-after: *widget-half-collapse-after

            - type: split-column
              max-columns: 1
              widgets:

                - <<: *reddit-simple
                  subreddit: movies
                  title: Discussions
                  search: flair:Discussion
                  sort-by: new
                  collapse-after: 6

                - <<: *reddit-cover
                  subreddit: Cinema
                  show-flairs: true
                  collapse-after: 6

                - <<: *reddit-cover
                  subreddit: BoxOffice
                  collapse-after: 6


            - <<: *backube-xml
              title: "Videos"
              options:
                collapse-after-rows: 8
              parameters:
                channel:
                  - UC7v3-2K1N84V67IF-WTRG-Q # Jeremy Jahns
                  - UCCqEeDAUf4Mg0GgEN658tkA # The Chris Stuckmans
                  - UCbiOAho0h23IMInURiESx1w # Dan Murrell
                  - UCrTNhL_yO3tPTdQ5XgmmWjA # RedLetterMedia
                  - UCUyvQV2JsICeLZP4c_h40kA # Thomas Flight
                  - UCSJPFQdZwrOutnmSFYtbstA # TheCriticalDrinker
                  - UCtu6CSE-BvaZUUGqW4tuEJA # Just One More Thing
