- name: "News" # ğŸŒ
  slug: news
  width: wide

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover
              subreddit: worldnews
              show-flairs: true
              collapse-after: 10

            - <<: *reddit-cover
              subreddit: geopolitics
              show-flairs: true
              collapse-after: 10

            - <<: *reddit-cover
              subreddit: News
              show-flairs: true
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/worldnews Top This Week
              subreddit: worldnews
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/geopolitics Top This Week
              subreddit: geopolitics
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/News Top This Week
              subreddit: News
              collapse-after: 10
