- name: News
  slug: news
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          options:
            collapse-after-rows: 2
          parameters:
            <<: *backube-video-parameters
            filter: kind="video"&&channel.tags?~"a1kphnyke2edl9f"

        - type: group
          vars:
            - &subreddits news+worldnews+politics+geopolitics+WorldEvents+inthenews+business+Economics+environment+GlobalTalk+PoliticalDiscussion+europe
          widgets:

            - <<: *xeddit-waterfall
              title: r/ global news & politics
              options:
                subreddit: *subreddits
                limit: 50

            - <<: *xeddit-waterfall
              title: Top This Week
              options:
                subreddit: *subreddits
                top-period: week
                sort-by: top
                limit: 50
