- name: "Mind" # ¿ ∞
  slug: psychology
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        perPage: 70
        filter: kind="video"&&channel.category="esmafhdlbw3esk7"&&(channel.tags?~"xvl2y8gux9p45r6"||channel.tags?~"w9hvtlrba7nwdy8")

  columns:

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: reddit communities
          options:
            subreddit: philosophy+DeepThoughts+askphilosophy+mentalhealth+depression+Anxiety+psychology
            min-column-width: 420
            limit: 50
