- name: "Science" # ðŸ”¬
  slug: science
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 4
          widgets:

            - <<: *reddit-cover
              subreddit: science

            - <<: *reddit-cover
              subreddit: askscience

            - <<: *reddit-cover
              subreddit: EverythingScience

            - <<: *backube-latest
              title: Videos
              options:
                collapse-after-rows: 8
                min-card-width-px: 240
              parameters:
                <<: *backube-video-parameters
                filter: channel.tags.name?="science"&&channel.category.code="sci"
