- name: "Science" # ğŸ”¬
  slug: science
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        perPage: 70
        filter: kind="video"&&channel.tags?~"cort70lkmsvxyfa"&&channel.category="esmafhdlbw3esk7"

  columns:

    - size: full
      widgets:

        - <<: *xeddit-waterfall
          title: reddit communities
          options:
            subreddit: science+askscience+EverythingScience
            min-column-width: 420
            limit: 50
