- name: "Science" # ðŸ”¬
  slug: science
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 4
          widgets:

            - <<: *reddit-cover
              subreddit: science

            - <<: *reddit-cover
              subreddit: askscience

            - <<: *reddit-cover
              subreddit: EverythingScience

            - <<: *backube-xml
              title: "Videos"
              options:
                collapse-after-rows: 8
                min-card-width-px: 240
              parameters:
                channel:
                  - UC1yNl2E66ZzKApQdRuTQ4tw # SabineHossenfelder
                  - UCciQ8wFcVoIIMi-lfu8-cjQ # Anton Petrov
                  - UCGHZpIpAWJQ-Jy_CeCdXhMA # CoolWorldsLab
                  - UCFbtcTaMFnOAP0pFO1L8hVw # Kyle Hill
