- name: "Shows" # ðŸ“º
  slug: shows
  width: wide
  head-widgets:

    - <<: *jellyfin-next-up

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/television/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search on r/tv
          bangs:
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/television/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query={QUERY}
            - title: Bingeflix
              shortcut: "!b"
              url: https://bingeflix.tv/search?tab=movies-tv&q={QUERY}
            - title: TÃ¼rkÃ§e AltyazÄ±
              shortcut: "!t"
              url: https://turkcealtyazi.org/find.php?cat=sub&find={QUERY}
            - title: Open Subtitles
              shortcut: "!o"
              url: https://www.opensubtitles.org/en/search2/moviename-{QUERY}/sublanguageid-tur,eng

        - type: bookmarks
          css-class: page-shows
          groups:
            - links:
                - title: Metacritic Tv
                  url: https://www.metacritic.com/tv/
                  icon: auto-invert ${ICONS_URL}/custom/metacritic.svg
                - title: Most Popular Tv
                  url: https://www.imdb.com/chart/tvmeter
                  icon: auto-invert ${ICONS_URL}/imdb-dark
                - title: Top 250 Tv
                  url: https://www.imdb.com/chart/toptv
                  icon: auto-invert ${ICONS_URL}/imdb-dark
            - <<: *links-subtitles
            - links:
                - title: Megathread
                  url: ${REDDIT_URL}/r/Piracy/wiki/megathread/movies_and_tv#wiki_.1F4D1_.279C_streaming

        - <<: *sonarr-calendar

        - <<: *jellyfin-episodes-list
          options:
            collapse-after: 10

    - size: full
      widgets:

        - type: group
          vars:
            - &subreddits television+TVDetails+televisionsuggestions+series
          widgets:

            - <<: *xeddit-waterfall
              title: r/ television & series & suggestions
              options:
                subreddit: *subreddits
                limit: 50

            - <<: *xeddit-waterfall
              title: Top This Week
              options:
                subreddit: *subreddits
                top-period: week
                sort-by: top
                limit: 50
