- name: "Space" # ğŸ‘½
  slug: space
  width: wide
  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 2
      parameters:
        <<: *backube-video-parameters
        perPage: 70
        filter: channel.tags.name?="space"&&channel.category.code="stem"

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover
              title: NASA
              subreddit: nasa

            - <<: *reddit-cover
              title: SpaceX
              subreddit: spacex

            - <<: *reddit-cover
              title: UFOs
              subreddit: UFOs
