- name: "Space" # ðŸ‘½
  slug: space
  width: wide
  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 4
          widgets:

            - <<: *reddit-cover
              title: NASA
              subreddit: nasa

            - <<: *reddit-cover
              title: SpaceX
              subreddit: spacex

            - <<: *reddit-cover
              title: UFOs
              subreddit: UFOs

            - <<: *backube-latest
              title: Videos
              options:
                collapse-after-rows: 8
                min-card-width-px: 240
              parameters:
                <<: *backube-video-parameters
                filter: channel.tags.name?="space"&&channel.category.code="sci"
