- name: "#sc"
  slug: starcitizen
  width: wide

  head-widgets:

    - <<: *twitch-category
      title: Twitch Star Citizen Streams [EN, TR]
      options:
        collapse-after-rows: 1
      body:
        query: |
          query {
            game(name: "Star Citizen") {
              streams(first: 30, options: { languages: ["EN", "TR"] }) {
                edges {
                  node {
                    id
                    createdAt
                    previewImageURL(width: 440, height: 248)
                    type
                    viewersCount
                    broadcaster {
                      login
                      displayName
                      profileImageURL(width: 300)
                      broadcastSettings {
                        title
                      }
                    }
                  }
                }
              }
            }
          }

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/starcitizen/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/starcitizen
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=star+citizen+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/search/?q={QUERY}

        - type: bookmarks
          groups:
            - title: My Account
              links:
                - title: Dashboard
                  url: https://robertsspaceindustries.com/en/account/dashboard
                - title: Hangar
                  url: https://robertsspaceindustries.com/en/account/pledges
                - title: Organization
                  url: https://robertsspaceindustries.com/en/account/organization
            - links:
                - title: S.C.Global
                  url: https://robertsspaceindustries.com/orgs/SCGLOBAL

        - type: bookmarks
          groups:
            - links:
                - title: Community Hub
                  url: https://robertsspaceindustries.com/community-hub
                - title: Spectrum
                  url: https://robertsspaceindustries.com/spectrum/community/SC
                - title: Progress Tracker
                  url: https://robertsspaceindustries.com/roadmap/progress-tracker/teams
                - title: Patch Notes
                  url: https://robertsspaceindustries.com/en/patch-notes#button
                - title: Dev Tracker
                  url: https://robertsspaceindustries.com/en/community/devtracker
                - title: Comm-Link
                  url: https://robertsspaceindustries.com/en/comm-link
            - color: 207.2 91.1 64.9
              links:
                - title: Galactapedia
                  url: https://robertsspaceindustries.com/galactapedia
                - title: Starmap
                  url: https://robertsspaceindustries.com/en/starmap
                - title: Ship Matrix
                  url: https://robertsspaceindustries.com/en/ship-matrix
                - title: Funding Goals
                  url: https://robertsspaceindustries.com/en/funding-goals
            - links:
                - title: Website
                  url: https://robertsspaceindustries.com/
                - title: X (Twitter)
                  url: https://x.com/RobertsSpaceInd
            - links:
                - title: Star Citizen Wiki
                  url: https://starcitizen.tools/

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-cover
              subreddit: starcitizen

            - <<: *reddit-cover-top-week
              title: Top This Week
              subreddit: starcitizen

            - <<: *videos-grid
              title: Videos
              channels:
                - UCTeLqJq1mXUX5WWoNXLmOIA #@RobertsSpaceInd
                - UCiPdjrLoUsyJh3XS7Aw7rzg #@Morphologis
                - UC7W5LTUy7DJYpx0cpVKJe0g #@BoredGamerUK
                - UCOblfLLbNni0_VUeGWhiKDw #@SaltEMike
                - UCiPdjrLoUsyJh3XS7Aw7rzg #@BoredGamerUK
                - UCiPdjrLoUsyJh3XS7Aw7rzg #@BoredGamerUK
