- name: "STEM+" # ðŸš€
  slug: stem-plus
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: kind="video"&&channel.category="esmafhdlbw3esk7"
