- name: "Tech" # ğŸ¤–
  slug: tech
  width: wide

  head-widgets:

    - <<: *reddit-base
      subreddit: Hardware+technology
      style: horizontal-cards

  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.category.code?="tech"
