- name: "Mahalle"
  slug: tr
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          options:
            collapse-after-rows: 2
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: kind="video"&&channel.language="c3u5dojqveecd62"&&channel.category!="5doguxzor0eekxd"

        - <<: *xeddit-waterfall
          title: GÃ¼ndem
          options:
            subreddit: Turkey+AskTurkey+Hukuk+Yatirim+istanbul+Izmir+Antalya+veYakinEvren+vlandiya+TarihiSeyler+secilmiskitap
            limit: 50
