- name: "Tv+" #❇️
  slug: tr
  width: wide

  head-widgets:

    - <<: *kick-streams
      title: Kick Top Streams [TR]
      parameters:
        language: tr
      options:
        collapse-after-rows: 1

  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          options:
            collapse-after-rows: 3
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.language.name="türkçe"&&channel.category.code!="ggwp"
