- name: "Muhit" #❇️
  slug: tr
  width: wide

  head-widgets:

    - <<: *kick-streams
      title: Kick Top Streams [TR]
      parameters:
        language: tr
      options:
        collapse-after-rows: 1

  columns:

    - size: small
      widgets:

        - <<: *reddit-simple
          subreddit: veYakinEvren
          cache: *long-cache
          collapse-after: 10

    - size: full
      widgets:

        - <<: *backube-latest
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.language.code="tr"&&channel.category.code!="ggwp"&&channel.category.code!="world"
