- name: "Vlogs" #ðŸŒ…
  slug: vlogs
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Vlogs
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: (channel.tags.name?="vlogs" && channel.language.name!="tÃ¼rkÃ§e")

        - <<: *backube-latest
          title: Travel
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: (channel.tags.name?="travel" && channel.language.name!="tÃ¼rkÃ§e")

        - <<: *backube-latest
          title: Outdoor
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.tags.name?="outdoor"
