- name: Vlogs
  slug: vlogs
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: kind="video"&&channel.category="k516tjizxpadzda"

        - <<: *backube-latest
          title: vlogs
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 7
            filter: kind="video"&&channel.tags?~"euqffttmgr6qssb"

        - <<: *backube-latest
          title: Travel
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 7
            filter: kind="video"&&channel.tags?~"hstxsacj27uw82c"

        - <<: *backube-latest
          title: Outdoor
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 7
            filter: kind="video"&&channel.tags?~"in6sgckqwvbe1tg"

        - <<: *backube-latest
          title: Camping
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 7
            filter: kind="video"&&channel.tags?~"6tyvuf4b04jbk2j"

        - <<: *backube-latest
          title: off-grid
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            perPage: 7
            filter: kind="video"&&channel.tags?~"il3ysp4xqg5kmbz"
