- name: "Vlogs" #ðŸŒ…
  slug: vlogs
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *videos-grid
          limit: 96
          channels:
            - UCtinbF-Q-fVthA0qrFQTgXQ # Casey Neistat
            - UCpp3cHR9TWVyXqL1AVw4XkA # Mike Okay
