- name: "Vlogs"
  slug: vlogs
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: daily
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="daily"

        - <<: *backube-latest
          title: Travel
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="travel"

        - <<: *backube-latest
          title: Outdoor
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="outdoor"

        - <<: *backube-latest
          title: Camping
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="camping"

        - <<: *backube-latest
          title: Social
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="social"

        - <<: *backube-latest
          title: Pranks
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: channel.tags.name?="pranks"
