- name: "#wildrift"
  slug: wr
  width: wide

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/wildrift/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/wildrift
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=wildrift+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/search/?q={QUERY}

        - type: twitch-channels
          channels: ["itzstu4rt"]
          title: Streamers

        - type: bookmarks
          groups:
            - links:
                - title: Account Management
                  icon: auto-invert ${ICONS_URL}/custom/riotgames.svg
                  url: https://account.riotgames.com/account
            - title: Wild Rift
              color: 196 86 62
              links:
                - title: Updates
                  url: https://wildrift.leagueoflegends.com/en-us/news/game-updates
                - title: Events
                  url: https://support-wildrift.riotgames.com/hc/en-us/sections/360010851213-Current-Events
                - title: WR Fire
                  url: https://www.wildriftfire.com
                - title: WR Meta
                  url: https://wr-meta.com

        - <<: *backube-latest
          title: "Official Wild Rift Videos"
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            filter: channel="UCd0ZomI5mPkrV735wul5kiw" #@wildrift

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: split-column
              max-columns: 1
              widgets:

                - <<: *reddit-cover
                  subreddit: wildrift
                  collapse-after: 10

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: wildrift
                  collapse-after: 10

            - type: group
              widgets:

                - <<: *backube-latest
                  title: "Videos"
                  options:
                    collapse-after-rows: 6
                  parameters:
                    <<: *backube-video-parameters
                    filter: channel.tags.name?="wild rift"

                - <<: *backube-latest
                  title: "Skin Spotlights"
                  options:
                    collapse-after-rows: 6
                  parameters:
                    <<: *backube-video-parameters
                    filter: channel="UCr8PQGDXXqC7fV-3aj8e5kA" #@SkinSpotlightsWildRift

            - type: split-column
              max-columns: 1
              widgets:

                - type: extension
                  url: ${GLIMPSE_URL}/riot/news
                  allow-potentially-dangerous-html: true
                  cache: *short-cache
                  headers:
                    x-glimpse-output: glance
                  parameters:
                    game: wildrift
                    limit: 20
                    collapseAfter: 5

                - <<: *twitch-category
                  title: Twitch Wildrift Streams [EN, TR]
                  options:
                    collapse-after-rows: 4
                  body:
                    query: |
                      query {
                        game(id: "514858") {
                          streams(first: 30, options: { languages: ["EN", "TR"] }) {
                            edges {
                              node {
                                id
                                createdAt
                                previewImageURL(width: 440, height: 248)
                                type
                                viewersCount
                                broadcaster {
                                  login
                                  displayName
                                  profileImageURL(width: 300)
                                  broadcastSettings {
                                    title
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
