- name: "#wildrift"
  slug: wr
  width: wide

  head-widgets:

    - type: split-column
      max-columns: 2
      widgets:

        - <<: *twitch-category
          title: Twitch Wildrift Streams [EN, TR]
          options:
            collapse-after-rows: 1
            min-card-width-px: 200
          body:
            query: |
              query {
                game(id: "514858") {
                  streams(first: 30, options: { languages: ["EN", "TR"] }) {
                    edges {
                      node {
                        id
                        createdAt
                        previewImageURL(width: 440, height: 248)
                        type
                        viewersCount
                        broadcaster {
                          login
                          displayName
                          profileImageURL(width: 300)
                          broadcastSettings {
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }

        - <<: *videos-horizontal
          title: Official Videos
          channels:
            - UCd0ZomI5mPkrV735wul5kiw #@wildrift

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/wildrift/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/wildrift
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=wildrift+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/search/?q={QUERY}

        - type: twitch-channels
          channels: ["itzstu4rt"]
          title: Streamers

        - type: bookmarks
          groups:
            - links:
                - title: Account Management
                  icon: auto-invert ${ICONS_URL}/custom/riotgames.svg
                  url: https://account.riotgames.com/account
            - title: Wild Rift
              color: 196 86 62
              links:
                - title: Updates
                  url: https://wildrift.leagueoflegends.com/en-us/news/game-updates
                - title: Events
                  url: https://support-wildrift.riotgames.com/hc/en-us/sections/360010851213-Current-Events
                - title: WR Fire
                  url: https://www.wildriftfire.com
                - title: WR Meta
                  url: https://wr-meta.com

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:

                - <<: *reddit-cover
                  subreddit: wildrift

                - <<: *reddit-cover-top-week
                  title: Top This Week
                  subreddit: wildrift


            - type: group
              widgets:

                - <<: *videos-grid
                  title: Videos
                  channels:
                    - UC3ofqT9q3pDxTd2UlNgSN0Q #@KanbaruWR
                    - UChcxXq9PudkG6K6gpFl1M-Q #@BrokenSupport
                    - UCowkr3QJ-TvX5siY3piQ2Xw #@RoyalWildRift
                    - UC-QXKllezN9OxLh6S-F8B9g #@OUTSIDERYT
                    - UCvASVZzW0X3ma8aYsFhVDJw #@RiftGuidesWildRift

                - <<: *videos-grid
                  title: Skin Spotlights
                  channels:
                    - UCr8PQGDXXqC7fV-3aj8e5kA #@SkinSpotlightsWildRift

            - type: extension
              url: ${GLIMPSE_URL}/riot/news
              allow-potentially-dangerous-html: true
              cache: *short-cache
              headers:
                x-glimpse-output: glance
              parameters:
                game: wildrift
                limit: 20
                collapseAfter: 10
