server:
  assets-path: /assets

branding:
  logo-text: â‹ˆ
  favicon-url: /assets/hub.ico
  app-name: "Hub"
  app-icon-url: /assets/hub.png

$include: /shared/index.yml

pages:
  # - $include: pages/home.yml
  - $include: pages/news.yml
  - $include: pages/tr.yml
  - $include: pages/paradise.yml
  - $include: pages/finance.yml
  - $include: pages/stem-plus.yml
  - $include: pages/science.yml
  - $include: pages/space.yml
  - $include: pages/psychology.yml
  - $include: pages/entertainment.yml
  - $include: pages/movies.yml
  - $include: pages/shows.yml
  - $include: pages/anime.yml
  - $include: pages/documentaries.yml
  - $include: pages/vlogs.yml
  - $include: pages/live.yml
  - $include: pages/hardware.yml
  - $include: pages/gaming/games.yml
  - $include: pages/gaming/league-of-legends.yml
  - $include: pages/gaming/wildrift.yml
  - $include: pages/gaming/crew.yml
  - $include: pages/gaming/gta.yml
  - $include: pages/gaming/starcitizen.yml
  # - $include: pages/cars.yml
