server:
  assets-path: /assets

branding:
  logo-text: â‹ˆ
  favicon-url: /assets/favicon-hub.ico
  app-name: "Glance Hub"

$include: /shared/index.yml

pages:
  # - $include: pages/home.yml
  - $include: pages/gundem.yml
  - $include: pages/news.yml
  - $include: pages/finance.yml
  - $include: pages/stem-plus.yml
  - $include: pages/science.yml
  - $include: pages/space.yml
  - $include: pages/psychology.yml
  - $include: pages/entertainment.yml
  - $include: pages/movies.yml
  - $include: pages/shows.yml
  - $include: pages/anime.yml
  - $include: pages/documentaries.yml
  - $include: pages/crime.yml
  - $include: pages/vlogs.yml
  - $include: pages/live.yml
  - $include: pages/tr.yml
  - $include: pages/gaming.yml
  - $include: pages/hardware.yml
  - $include: pages/league-of-legends.yml
  - $include: pages/wildrift.yml
  - $include: pages/crew.yml
  - $include: pages/gta.yml
  - $include: pages/starcitizen.yml
  # - $include: pages/cars.yml
