- name: "#backend" #
  slug: backend
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/backend/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/backend

        - type: bookmarks
          groups:
            - title: Dev Containers
              links:
                - title: Templates
                  url: https://containers.dev/templates
                - title: Features
                  url: https://containers.dev/features

        - <<: *github-releases
          title: Headless CMS
          repositories:
            - pocketbase/pocketbase
            - directus/directus
            - trailbaseio/trailbase
            # - strapi/strapi
            # - payloadcms/payload

        - <<: *github-releases
          title: Backend
          repositories:
            - nitrojs/nitro
            - honojs/hono
            - unjs/h3
            - unjs/db0
            - unkeyed/unkey
            - elysiajs/elysia

        - <<: *github-releases
          title: JS Runtime
          repositories:
            - denoland/deno
            - nodejs/node
            - oven-sh/bun

        - <<: *github-releases
          title: Software
          repositories:
            - usebruno/bruno
            - mountain-loop/yaak
            - httpie/desktop

        - <<: *html-node

        - type: bookmarks
          groups:
            - links:
                - title: Public APIs
                  url: https://github.com/public-apis/public-apis#readme
                - title: Awesome Node.js
                  url: https://github.com/sindresorhus/awesome-nodejs#readme

    - size: full
      widgets:

        - type: group
          widgets:

            - <<: *reddit-simple-full
              subreddit: Backend

            - <<: *reddit-simple-top-week
              title: Top This Week
              subreddit: Backend
              collapse-after: 30

    - size: full
      widgets:

        - type: group
          widgets:

            - <<: *reddit-simple
              subreddit: node

            - <<: *reddit-simple-top-week
              title: Top This Week
              subreddit: node

        - type: group
          widgets:

            - <<: *reddit-simple
              subreddit: deno

            - <<: *reddit-simple-top-week
              title: Top This Week
              subreddit: deno
