- name: "DevOps" # ğŸ› ï¸
  slug: devops
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: DevOps Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="avd23828y2jcz8j"&&(channel.tags?~"b4mmmayzbubp6q1"||title~"devops")

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/devops/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/devops

        - type: bookmarks
          groups:
            - links:
                - title: Dynamic DevOps Roadmap
                  url: https://roadmap.devopshive.net
                - title: The Book of Secret Knowledge
                  url: https://github.com/trimstray/the-book-of-secret-knowledge
                - title: DevOps Exercises
                  url: https://github.com/bregman-arie/devops-exercises
                - title: Awesome Scalability
                  url: https://github.com/binhnguyennus/awesome-scalability
                - title: 90 Days of DevOps
                  url: https://github.com/MichaelCade/90DaysOfDevOps
            - links:
                - title: Awesome Sysadmin
                  url: https://github.com/awesome-foss/awesome-sysadmin?tab=readme-ov-file#awesome-sysadmin
            - links:
                - title: Awesome Docker
                  url: https://github.com/veggiemonk/awesome-docker?tab=readme-ov-file#awesome-docker--
                - title: DevOps with Docker
                  url: https://devopswithdocker.com
                - title: Docker Security
                  url: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

        - <<: *github-releases
          repositories:
            - semaphoreui/semaphore
            - opentofu/opentofu
            - ansible/ansible

        - <<: *github-releases
          repositories:
            - openbao/openbao
            - hashicorp/vault
            - Infisical/infisical
            - jesseduffield/lazydocker

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: devops

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: sysadmin

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: linuxadmin

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: networking

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: docker

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: podman

            - <<: *reddit-simple
              collapse-after: *widget-half-collapse-after
              subreddit: ansible
