- name: "Env" #
  slug: env
  width: wide
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 6
          widgets:
            - type: bookmarks
              hide-header: true
              groups:
                - title: PocketBase
                  hide-arrow: true
                  links:
                    - title: /pocketbase
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/pocketbase/pocketbase
                    - title: /shablon
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/pocketbase/shablon
                - links:
                    - title: API rules and filters
                      url: https://pocketbase.io/docs/api-rules-and-filters/
                    - title: Working with relations
                      url: https://pocketbase.io/docs/working-with-relations/
                    - title: Extending PocketBase
                      url: https://pocketbase.io/docs/use-as-framework/
                    - title: Going to production
                      url: https://pocketbase.io/docs/going-to-production/
                    - title: Web APIs reference
                      url: https://pocketbase.io/docs/api-records/

            - type: bookmarks
              hide-header: true
              groups:
                - hide-arrow: true
                  links:
                    - title: Tailwind CSS
                      icon: auto-invert ${ICONS_URL}/custom/tailwindcss.svg
                      url: https://tailwindcss.com
                    - title: Tailwind UI
                      icon: auto-invert ${ICONS_URL}/custom/tailwindcss.svg
                      url: https://tailwindcss.com/plus/ui-blocks
                - title: UI
                  color: 129 68 58
                  links:
                    - title: Origin UI
                      url: https://originui.com
                    - title: Tremor
                      url: https://tremor.so
                    - title: shadcn/ui
                      url: https://ui.shadcn.com
                - title: Icons
                  color: 188 70 50
                  links:
                    - title: Simple Icons
                      url: https://simpleicons.org
                    - title: Hero Icons
                      url: https://heroicons.com
                - links:
                    - title: Webdev Resources
                      url: https://github.com/RitikPatni/Front-End-Web-Development-Resources
                    - title: Flexbox
                      url: https://flexbox.tech/
                    - title: OKLCH Colors
                      url: https://oklch.fyi/gradients

            - type: bookmarks
              hide-header: true
              groups:
                - hide-arrow: true
                  links:
                    - title: MDN Web Docs
                      icon: auto-invert ${ICONS_URL}/custom/mdnwebdocs.svg
                      url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
                    - title: JSR
                      icon: auto-invert ${ICONS_URL}/custom/jsr.svg
                      url: https://jsr.io/
                    - title: JSFiddle
                      icon: auto-invert ${ICONS_URL}/custom/jsfiddle.svg
                      url: https://jsfiddle.net/
                - links:
                    - title: JavaScript Snippets
                      icon: auto-invert ${ICONS_URL}/custom/30secondsofcode.svg
                      url: https://www.30secondsofcode.org/js/p/1
                    - title: 33 JS Concepts
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/leonardomso/33-js-concepts
                    - title: Javascript Algorithms
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/trekhleb/javascript-algorithms
                    - title: You Don't Know JS
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/getify/You-Dont-Know-JS
                    - title: Modern JS Cheatsheet
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/mbeaudru/modern-js-cheatsheet
                    - title: Learn Regex
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/ziishaned/learn-regex

            - type: bookmarks
              hide-header: true
              groups:
                - hide-arrow: true
                  links:
                    - title: PostgreSQL
                      icon: auto-invert ${ICONS_URL}/custom/postgresql.svg
                      url: https://www.postgresql.org/download/
                    - title: MongoDB
                      icon: auto-invert ${ICONS_URL}/custom/mongodb.svg
                      url: https://www.mongodb.com/try/download/community
                    - title: SQLite
                      icon: auto-invert ${ICONS_URL}/custom/sqlite.svg
                      url: https://www.sqlite.org/download.html
                - links:
                    - title: Convex
                      url: https://www.convex.dev/
                    - title: Convex Docs
                      url: https://docs.convex.dev/home

            - type: bookmarks
              hide-header: true
              groups:
                - title: React
                  links:
                    - title: TanStack
                      url: https://tanstack.com/
                    - title: Awesome React
                      url: https://github.com/enaqx/awesome-react#readme
                    - title: Awesome React Components
                      url: https://github.com/brillout/awesome-react-components#readme
                - title: Next
                  links:
                    - title: Docs
                      url: https://nextjs.org/docs/app/getting-started/installation
                    - title: Examples
                      url: https://nextjs.org/docs/app/examples
                    - title: Blog
                      url: https://nextjs.org/blog
                    - title: API
                      url: https://nextjs.org/docs/app/api-reference

            - type: bookmarks
              hide-header: true
              groups:
                - hide-arrow: true
                  links:
                    - title: Vue.js
                      icon: auto-invert ${ICONS_URL}/custom/vuedotjs.svg
                      url: https://vuejs.org/guide/introduction.html
                    - title: Vueuse
                      icon: auto-invert ${ICONS_URL}/custom/vueuse.svg
                      url: https://vueuse.org/guide/
                    - title: Awesome Vue
                      icon: auto-invert ${ICONS_URL}/github-dark
                      url: https://github.com/vuejs/awesome-vue#readme
                - title: Nuxt
                  links:
                    - title: Docs
                      url: https://nuxt.com/docs/getting-started/introduction
                    - title: Modules
                      url: https://nuxt.com/modules
                    - title: Guide
                      url: https://nuxt.com/docs/guide
                    - title: API
                      url: https://nuxt.com/docs/api

            - type: bookmarks
              hide-header: true
              groups:
                - links:
                    - title: Winget.run
                      url: https://winget.run/
                - title: Utilities
                  links:
                    - title: Massgrave.dev
                      url: https://massgrave.dev
                    - title: Unattended Generator
                      url: https://schneegans.de/windows/unattend-generator
                    - title: Unattended Winstall
                      url: https://github.com/memstechtips/UnattendedWinstall
                - title: Developer Tools
                  links:
                    - title: Package Manager
                      url: https://learn.microsoft.com/en-us/windows/package-manager
                    - title: Subsystem for Linux
                      url: https://learn.microsoft.com/en-us/windows/wsl
                    - title: PowerToys
                      url: https://learn.microsoft.com/en-us/windows/powertoys
                - title: Sysinternals
                  links:
                    - title: What's New
                      url: https://learn.microsoft.com/en-us/sysinternals/# whats-new-rss-icon
                    - title: TCPView
                      url: https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview
                    - title: Process Monitor
                      url: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

            - type: bookmarks
              groups:
                - title: Awesome Lists
                  color: 47 92 53
                  links:
                    - title: Privacy
                      url: https://github.com/Lissy93/awesome-privacy
                    - title: Podcasts
                      url: https://github.com/rShetty/awesome-podcasts
                    - title: Sysadmin
                      url: https://github.com/awesome-foss/awesome-sysadmin
                    - title: Scalability
                      url: https://github.com/binhnguyennus/awesome-scalability
                    - title: Docker
                      url: https://github.com/veggiemonk/awesome-docker
                    - title: Linux Software
                      url: https://github.com/luong-komorebi/Awesome-Linux-Software
                    - title: Selfhosted
                      url: https://github.com/awesome-selfhosted/awesome-selfhosted

            - type: bookmarks
              hide-header: true
              groups:
                - links:
                    - title: Dynamic DevOps Roadmap
                      url: https://roadmap.devopshive.net
                    - title: The Book of Secret Knowledge
                      url: https://github.com/trimstray/the-book-of-secret-knowledge
                    - title: DevOps Exercises
                      url: https://github.com/bregman-arie/devops-exercises
                    - title: Awesome Scalability
                      url: https://github.com/binhnguyennus/awesome-scalability
                    - title: 90 Days of DevOps
                      url: https://github.com/MichaelCade/90DaysOfDevOps
                - links:
                    - title: Awesome Sysadmin
                      url: https://github.com/awesome-foss/awesome-sysadmin?tab=readme-ov-file#awesome-sysadmin
                - links:
                    - title: Awesome Docker
                      url: https://github.com/veggiemonk/awesome-docker?tab=readme-ov-file#awesome-docker--
                    - title: DevOps with Docker
                      url: https://devopswithdocker.com
                    - title: Docker Security
                      url: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

            - type: bookmarks
              hide-header: true
              groups:
                - title: Dev Containers
                  links:
                    - title: Templates
                      url: https://containers.dev/templates
                    - title: Features
                      url: https://containers.dev/features

            - type: bookmarks
              groups:
                - title: Awesome Lists
                  color: 47 92 53
                  links:
                    - title: Privacy
                      url: https://github.com/Lissy93/awesome-privacy
                    - title: Podcasts
                      url: https://github.com/rShetty/awesome-podcasts
                    - title: Sysadmin
                      url: https://github.com/awesome-foss/awesome-sysadmin
                    - title: Scalability
                      url: https://github.com/binhnguyennus/awesome-scalability
                    - title: Docker
                      url: https://github.com/veggiemonk/awesome-docker
                    - title: Linux Software
                      url: https://github.com/luong-komorebi/Awesome-Linux-Software
                    - title: Selfhosted
                      url: https://github.com/awesome-selfhosted/awesome-selfhosted

            - <<: *github-releases
              title: Web Apps
              repositories:
                - twentyhq/twenty
                - gitroomhq/postiz-app
                - Budibase/budibase
                - nocodb/nocodb
                - excalidraw/excalidraw

            - <<: *github-releases
              title: Linux
              repositories:
                - YaLTeR/niri
                - lutris/lutris
                - aristocratos/btop
                - facebookincubator/below

            - <<: *github-releases
              title: Apps
              repositories:
                - DevToys-app/DevToys
                - mr-karan/doggo
                - mountain-loop/yaak
                - microsoft/PowerToys
                - winsiderss/systeminformer
                - ChrisTitusTech/winutil
                - HotCakeX/Harden-Windows-Security
                - windirstat/windirstat

            - <<: *github-releases
              title: Media Players
              repositories:
                - obsproject/obs-studio
                - zhongfly/mpv-winbuild

            - <<: *github-releases
              title: Code Editors
              repositories:
                - zed-industries/zed
                - microsoft/vscode
