- name: Go
  slug: go
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="avd23828y2jcz8j"&&(channel.tags?~"wnemweqicm5djst"||title~"golang")

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/golang/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=golang+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/golang/search?q={QUERY}&restrict_sr=on&sort=new&t=all

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: Documentation
                  icon: auto-invert ${ICONS_URL}/golang-dark
                  url: https://go.dev/doc/
                - title: Standard library
                  url: https://pkg.go.dev/std
                - title: Packages
                  url: https://pkg.go.dev/
                - title: How to Write Go Code
                  url: https://go.dev/doc/code#Introduction

        - type: bookmarks
          groups:
            - links:
                - title: awesome-go
                  url: https://github.com/avelino/awesome-go
                - title: go-standards
                  url: https://github.com/golang-standards/project-layout
                - title: go-patterns
                  url: https://github.com/tmrts/go-patterns
                - title: go-datastructures
                  url: https://github.com/Workiva/go-datastructures
                - title: gofiber
                  url: https://github.com/gofiber/fiber
                - title: gjson
                  url: https://github.com/tidwall/gjson
            - links:
                - title: gjson Playground
                  url: https://gjson.dev/

        - <<: *github-releases
          repositories:
            - hibiken/asynq
            - pocketbase/pocketbase

        - <<: *github-releases
          repositories:
            - go-gorm/gorm
            - wailsapp/wails
            - gocolly/colly
            - uber-go/zap

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: golang/go

            - <<: *reddit-simple
              subreddit: golang
              collapse-after: 22

            - <<: *reddit-simple-top-month
              title: r/golang Top This Month
              subreddit: golang
              collapse-after: 22

            - <<: *reddit-simple-top-week
              title: r/golang Top This Week
              subreddit: golang
              collapse-after: 15
