- name: "Javascript" # ğŸŸ¡
  slug: javascript
  width: wide

  head-widgets:

    - <<: *backube-base
      hide-header: true
      title: "Javascript Videos"
      options:
        collapse-after-rows: 1
      parameters:
        perPage: 32
        channel:
          - UCswG6FSbgZjbWtdf_hMLaow #@mattpocockuk
          - UCmXmlB4-HJytD7wek0Uo97A #JavaScript Mastery
        keyword:
          - javascript
          - typescript

  columns:

    - size: small
      widgets:

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: MDN Web Docs
                  icon: auto-invert ${ICONS_URL}/custom/mdnwebdocs.svg
                  url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
                - title: JSR
                  icon: auto-invert ${ICONS_URL}/custom/jsr.svg
                  url: https://jsr.io/
                - title: JSFiddle
                  icon: auto-invert ${ICONS_URL}/custom/jsfiddle.svg
                  url: https://jsfiddle.net/
            - links:
                - title: JavaScript Snippets
                  icon: auto-invert ${ICONS_URL}/custom/30secondsofcode.svg
                  url: https://www.30secondsofcode.org/js/p/1
                - title: 33 JS Concepts
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/leonardomso/33-js-concepts
                - title: Javascript Algorithms
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/trekhleb/javascript-algorithms
                - title: You Don't Know JS
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/getify/You-Dont-Know-JS
                - title: Modern JS Cheatsheet
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/mbeaudru/modern-js-cheatsheet
                - title: Learn Regex
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/ziishaned/learn-regex

        - type: bookmarks
          hide-header: true
          groups:
            - color: 320 100 76
              links:
                - title: Zod
                  icon: auto-invert ${ICONS_URL}/custom/zod.svg
                  url: https://zod.dev/api
                - title: Zod Tutorial
                  url: https://www.totaltypescript.com/tutorials/zod
                - title: Zod Playground
                  url: https://zod-playground.vercel.app/

        - <<: *github-releases
          repositories:
            - colinhacks/zod
            - Effect-TS/effect
            - microsoft/TypeScript
            - lodash/lodash
            - supermacro/neverthrow

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: javascript

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: javascript

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: javascript

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: typescript

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: typescript

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: typescript

            - <<: *reddit-simple-full
              subreddit: learnjavascript
