- name: "Linux" # üêß
  slug: linux
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/linux/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/linux

        - type: bookmarks
          groups:
            - links:
                - title: Awesome Linux Software
                  url: https://github.com/luong-komorebi/Awesome-Linux-Software#applications

        - <<: *github-releases
          title: Software
          repositories:
            - YaLTeR/niri
            - lutris/lutris
            - aristocratos/btop
            - facebookincubator/below

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:
                - <<: *reddit-simple-full
                  title: Hot Today
                  subreddit: linux

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: linux

            - type: split-column
              max-columns: 1
              widgets:

                - <<: *reddit-simple
                  collapse-after: *widget-half-collapse-after
                  subreddit: fedora

                - <<: *reddit-simple
                  collapse-after: *widget-half-collapse-after
                  subreddit: ubuntu

            - <<: *backube-latest
              title: Videos
              options:
                collapse-after-rows: 8
                min-card-width-px: 240
              parameters:
                <<: *backube-video-parameters
                filter: kind="video"&&channel.category="avd23828y2jcz8j"&&(channel.tags?~"2yjgcq6k0gcoelx"||title~"linux")
