- name: "News" # ğŸ“¢
  slug: news
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="avd23828y2jcz8j"&&channel.tags?~"3jjmo5koop3f60o"

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: hacker-news
              cache: *default-cache
              limit: 20
              collapse-after: 10

            - <<: *reddit-simple
              subreddit: programming
              collapse-after: 10

            - <<: *reddit-cover
              subreddit: technology
              collapse-after: 8

            - type: lobsters
              cache: *default-cache
              sort-by: hot
              limit: 20
              collapse-after: 10

            - <<: *reddit-simple-top-week
              title: r/programming Top This Week
              subreddit: programming
              collapse-after: 10

            - <<: *reddit-cover-top-week
              title: r/technology Top This Week
              subreddit: technology
              collapse-after: 8
