- name: "News" # ğŸ“¢
  slug: news
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: "@Theo"
      hide-header: true
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: channel="UCbRP3c757lWg9M-U7TyEkXA"

  columns:

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: hacker-news
              cache: *default-cache
              limit: 20
              collapse-after: 10

            - type: group
              widgets:

                - <<: *reddit-simple
                  subreddit: programming
                  collapse-after: 10

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: programming
                  collapse-after: 10

            - <<: *backube-latest
              title: dev
              options:
                collapse-after-rows: 6
              parameters:
                <<: *backube-video-parameters
                filter: (channel.category.code="dev" && channel!="UCbRP3c757lWg9M-U7TyEkXA")

            - type: lobsters
              cache: *default-cache
              sort-by: hot
              limit: 20
              collapse-after: 10

            - type: group
              widgets:

                - <<: *reddit-simple
                  subreddit: technology
                  collapse-after: 10

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: technology
                  collapse-after: 10
