- name: "Podcasts" # ğŸ™ï¸
  slug: podcasts
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *videos-grid
          collapse-after-rows: 1
          playlists:
            - PLLnpHn493BHHNUfHN5lDf11UD8jQ5Bpzl # Syntax - Tasty Web Development Treats
            - PL2Fq-K0QdOQiJpufsnhEd1z3xOv2JMHuk # ThePrimeTime - The Standup
            - PL2Fq-K0QdOQhLEX54hNhsTRvKnCSQrzyn # ThePrimeTime - TopShelf
            - PLX6ivsCcfHDOzMIUioOofyF-h-niZL6Qj # Beyond Coding Podcast
            - PLWKjhJtqVAbm04DK8TSUCRheRjW2P9TR7 # @freecodecamp

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 3
          parameters:
            <<: *backube-video-parameters
            filter: channel.category.code="dev"&&channel.tags.name?="podcasts"
