- name: "React" # ðŸ”µ
  slug: react
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: google
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=nextjs+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/nextjs/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Github
              shortcut: "!g"
              url: https://github.com/vercel/next.js/issues?q={QUERY}

        - type: bookmarks
          groups:
            - links:
                - title: TanStack
                  url: https://tanstack.com/
                - title: Awesome React
                  url: https://github.com/enaqx/awesome-react#readme
                - title: Awesome React Components
                  url: https://github.com/brillout/awesome-react-components#readme

        - type: bookmarks
          title: Next
          css-class: list-item-inline
          groups:
            - links:
                - title: Docs
                  url: https://nextjs.org/docs/app/getting-started/installation
                - title: Examples
                  url: https://nextjs.org/docs/app/examples
                - title: Blog
                  url: https://nextjs.org/blog
                - title: API
                  url: https://nextjs.org/docs/app/api-reference

        - <<: *github-releases
          title: React
          repositories:
            - vercel/next.js
            - facebook/react
            - TanStack/query

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: vercel/next.js

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  title: React
                  subreddit: reactjs

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: reactjs

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: reactjs

            - <<: *videos-grid
              channels:
                - UCf6AGqO98eGk11nfazociVQ # ByteGrad
                - UCZMli3czZnd1uoc1ShTouQw # leerob
                - UCsrVDPJBYeXItETFHG0qzyw # WebDevCody
                - UCvGwM5woTl13I-qThI4YMCg # joshtriedcoding

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  title: Next
                  subreddit: nextjs

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: nextjs

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: nextjs
