- name: "Security" # ğŸ›¡ï¸
  slug: nulsec
  width: wide

  head-widgets:

    - <<: *backube-latest
      hide-header: true
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: channel.tags.name?="cybersecurity"

  columns:

    - size: small
      widgets:
        - type: search
          search-engine: ${REDDIT_URL}/r/cybersecurity/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/cybersecurity

        - type: bookmarks
          groups:
            - links:
                - title: Privacy Guides
                  url: https://www.privacyguides.org/en/desktop-browsers/
                - title: Cover Your Tracks
                  url: https://coveryourtracks.eff.org/
                - title: Am i unique?
                  url: https://amiunique.org/fingerprint
                - title: BrowserLeaks
                  url: https://browserleaks.com/
                - title: WhatIsMyBrowser
                  url: https://www.whatismybrowser.com/
                - title: VirusTotal
                  url: https://www.virustotal.com/
                - title: Awesome Privacy
                  url: https://github.com/pluja/awesome-privacy
                - title: Awesome Hacking
                  url: https://github.com/Hack-with-Github/Awesome-Hacking

        - <<: *github-repository
          repository: un-nf/404

        - type: videos
          style: vertical-list
          css-class: hide-details video-list
          title: Darknet Diaries
          playlists:
            - PLtN43kak3fFEEDNo0ks9QVKYfQpT2yUEo # Darknet Diaries

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: cybersecurity

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: cybersecurity

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: hacking

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: hacking

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: netsec

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: netsec
