- name: "Selfhost" # ☢️
  slug: selfhost
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/selfhosted/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/selfhosted
          bangs:
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/selfhosted/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=selfhosted+{QUERY}

        - type: bookmarks
          groups:
            - links:
                - title: Selfh.st Apps
                  icon: auto-invert ${ICONS_URL}/selfh-st-dark
                  url: https://selfh.st/apps
                - title: Awesome-Selfhosted
                  icon: auto-invert ${ICONS_URL}/custom/awesomelists.svg
                  url: https://awesome-selfhosted.net/
                - title: LinuxServer Images
                  icon: auto-invert ${ICONS_URL}/linuxserver-io-dark
                  url: https://docs.linuxserver.io/images/
            - links:
                - title: Selfh.st Icons
                  icon: auto-invert ${ICONS_URL}/selfh-st-dark
                  url: https://selfh.st/icons
                - title: SimpleIcons
                  icon: auto-invert ${ICONS_URL}/custom/simpleicons.svg
                  url: https://simpleicons.org/
                - title: HeroIcons
                  url: https://heroicons.com/
            - color: 31 100 71
              links:
                - title: Awesome Compose
                  url: https://github.com/docker/awesome-compose
                - title: Compose Examples
                  url: https://github.com/Haxxnet/Compose-Examples/tree/main/examples
                - title:  Self Hosting Guide
                  url: https://github.com/mikeroyal/Self-Hosting-Guide
                - title: Trash Guides
                  url: https://trash-guides.info
                - title: Geek's Cookbook
                  url: https://geek-cookbook.funkypenguin.co.nz/

        - type: bookmarks
          title: Docker
          css-class: list-item-inline
          groups:
            - color: 223 90 50
              links:
                - title: Hub
                  url: https://hub.docker.com/search?badges=official&badges=verified_publisher
                - title: Services
                  url: https://docs.docker.com/reference/compose-file/services/
                - title: Networks
                  url: https://docs.docker.com/reference/compose-file/networks/
                - title: Dockerfile
                  url: https://docs.docker.com/reference/dockerfile/
                - title: Manuals
                  url: https://docs.docker.com/manuals/
                - title: Samples
                  url: https://docs.docker.com/reference/samples/

        - <<: *github-releases
          title: Core
          collapse-after: 10
          show-source-icon: true
          repositories:
            - go-gitea/gitea
            - traefik/traefik
            - AdguardTeam/AdGuardHome
            - moghtech/komodo
            - pocket-id/pocket-id
            - rustmailer/bichon
            - nicotsx/zerobyte
            - immich-app/immich
            - jellyfin/jellyfin
            - Sonarr/Sonarr
            - radarr/radarr
            - glanceapp/glance
            - umami-software/umami
            - amir20/dozzle
            - binwiederhier/ntfy
            - henrygd/beszel
            - advplyr/audiobookshelf
            - autobrr/qui
            - dokploy/dokploy
            - steveiliop56/tinyauth
            - thomiceli/opengist
            - dani-garcia/vaultwarden
            # - open-webui/open-webui
            # - authelia/authelia
            # - qdm12/gluetun
            # - fosrl/pangolin
            # - caddyserver/caddy
            # - prowlarr/prowlarr
            # - Readarr/Readarr
            # - Lidarr/Lidarr
            # - flaresolverr/flaresolverr
            # - iv-org/invidious
            # - docmost/docmost
            # - home-assistant/core
            # - sharevb/it-tools
            # - kieraneglin/pinchflat
            # - codeberg:forgejo/forgejo

        #  - type: rss
        #    cache: *long-cache
        #    title: Podcasts
        #    feeds:
        #      - url: https://media.rss.com/theselfhostcast/feed.xml
        #        title: Self-Host Cast

        # - <<: *github-releases
        #   title: Docker Hub
        #   collapse-after: 5
        #   show-source-icon: true
        #   repositories:
        #     - dockerhub:traefik
        #     - dockerhub:gitea/gitea
        #     - dockerhub:linuxserver/socket-proxy
        #     - dockerhub:linuxserver/jellyfin
        #     - dockerhub:linuxserver/sonarr
        #     - dockerhub:linuxserver/radarr
        #     - dockerhub:linuxserver/bazarr
        #     - dockerhub:linuxserver/prowlarr
        #     - dockerhub:flaresolverr/flaresolverr
        #     - dockerhub:linuxserver/qbittorrent

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - type: split-column
              max-columns: 1
              widgets:

                - type: group
                  widgets:

                    - <<: *reddit-simple-full
                      collapse-after: 15
                      subreddit: selfhosted

                - type: group
                  widgets:

                    - <<: *reddit-simple-top-week
                      collapse-after: 10
                      title: Top This Week
                      subreddit: selfhosted

                    - <<: *reddit-simple-top-month
                      collapse-after: 10
                      title: Month
                      subreddit: selfhosted

            - type: split-column
              max-columns: 1
              widgets:

                - <<: *github-repository
                  title: Glance Repository
                  repository: glanceapp/glance

                - type: group
                  widgets:

                    - <<: *reddit-simple
                      collapse-after: 5
                      subreddit: docker

                    - <<: *reddit-simple-top-week
                      collapse-after: 5
                      title: Top This Week
                      subreddit: docker

                - type: group
                  widgets:

                    - <<: *reddit-simple
                      subreddit: Proxmox
                      collapse-after: 5

                    - <<: *reddit-simple-top-week
                      title: Top This Week
                      subreddit: Proxmox
                      collapse-after: 5

                - type: group
                  widgets:

                    - <<: *reddit-simple
                      subreddit: podman
                      collapse-after: 5

                    - <<: *reddit-simple-top-week
                      title: Top This Week
                      subreddit: podman
                      collapse-after: 5

            - type: group
              widgets:

                - <<: *backube-latest
                  title: Videos
                  options:
                    collapse-after-rows: 8
                  parameters:
                    <<: *backube-video-parameters
                    filter: channel.category.code="dev"&&(channel.tags.name?="selfhost"||title~"selfhost"||title~"self host")

                - <<: *backube-latest
                  title: Docker
                  options:
                    collapse-after-rows: 8
                  parameters:
                    <<: *backube-video-parameters
                    filter: channel.category.code="dev"&&title~"docker"
