- name: "Software" # ðŸ’¿
  slug: software
  width: wide
  columns:

    - size: small
      widgets:

    - size: full
      widgets:

        - <<: *reddit-simple-full
          subreddit: software

    - size: full
      widgets:

        - <<: *reddit-simple-full
          subreddit: opensource
