- name: "Svelte" # ðŸŸ 
  slug: svelte
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: https://github.com/sveltejs/svelte/issues?q={QUERY}
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=svelte+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/sveltejs/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Github
              shortcut: "!g"
              url: https://github.com/sveltejs/svelte/issues?q={QUERY}

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: Blog
                  icon: auto-invert ${ICONS_URL}/custom/svelte.svg
                  url: https://svelte.dev/blog
            - links:
                - title: Getting Started
                  url: https://svelte.dev/docs/svelte/overview
                - title: SvelteKit
                  url: https://svelte.dev/docs/kit/introduction
                - title: Tutorial
                  url: https://svelte.dev/tutorial
            - links:
                - title: Awesome Svelte
                  url: https://github.com/TheComputerM/awesome-svelte#readme

        - <<: *github-releases
          repositories:
            - sveltejs/svelte
            - svecosystem/runed
            - huntabyte/shadcn-svelte
            - ciscoheat/sveltekit-superforms
            - x0k/svelte-jsonschema-form

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: sveltejs/svelte

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: sveltejs

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: sveltejs

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: sveltejs

            - <<: *backube-latest
              title: Videos
              options:
                collapse-after-rows: 8
              parameters:
                <<: *backube-video-parameters
                filter: channel.category.code="dev"&&(channel.tags.name?="sveltejs"||title~"svelte")

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  subreddit: SvelteKit

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: SvelteKit

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: SvelteKit
