- name: "Svelte" # ğŸŸ 
  slug: svelte
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="avd23828y2jcz8j"&&(channel.tags?~"lis8hl5ka8ngbyo"||title~"svelte")

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: https://github.com/sveltejs/svelte/issues?q={QUERY}
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=svelte+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/sveltejs/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Github
              shortcut: "!g"
              url: https://github.com/sveltejs/svelte/issues?q={QUERY}

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: Blog
                  icon: auto-invert ${ICONS_URL}/custom/svelte.svg
                  url: https://svelte.dev/blog
            - links:
                - title: Getting Started
                  url: https://svelte.dev/docs/svelte/overview
                - title: SvelteKit
                  url: https://svelte.dev/docs/kit/introduction
                - title: Tutorial
                  url: https://svelte.dev/tutorial
            - links:
                - title: Awesome Svelte
                  url: https://github.com/TheComputerM/awesome-svelte#readme

        - <<: *github-releases
          repositories:
            - sveltejs/svelte
            - svecosystem/runed
            - huntabyte/shadcn-svelte
            - ciscoheat/sveltekit-superforms
            - x0k/svelte-jsonschema-form

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: sveltejs/svelte

            - <<: *reddit-simple
              subreddit: sveltejs
              collapse-after: 22

            - <<: *reddit-simple-top-month
              title: r/sveltejs Top This Month
              subreddit: sveltejs
              collapse-after: 22

            - <<: *reddit-simple-top-week
              title: r/sveltejs Top This Week
              subreddit: sveltejs
              collapse-after: 15
