- name: "Learn" # ðŸ”·
  slug: tutorials
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 8
          parameters:
            <<: *backube-video-parameters
            filter: channel.category.code="dev"&&(channel.tags.name?="tutorials"||title~"tutorial")
