- name: "Videos" # ðŸ”·
  slug: videos
  width: wide
  columns:

    - size: full
      widgets:

        - <<: *backube-latest
          title: Videos
          options:
            collapse-after-rows: 4
          parameters:
            <<: *backube-video-parameters
            perPage: 70
            filter: channel.category.code="dev"
