- name: "Vue" # ğŸŸ¢
  slug: vue
  width: wide

  head-widgets:

    - <<: *backube-latest
      title: Videos
      options:
        collapse-after-rows: 1
      parameters:
        <<: *backube-video-parameters
        filter: kind="video"&&channel.category="avd23828y2jcz8j"&&(channel.tags?~"byfw2x4lpn7dy0g"||channel.tags?~"cl6ei9ysqzm107w"||title~"vuejs"||title~"nuxtjs")

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: https://github.com/nuxt/nuxt/issues?q={QUERY}
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=nuxt+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/Nuxt/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Github
              shortcut: "!g"
              url: https://github.com/nuxt/nuxt/issues?q={QUERY}

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: Vue.js
                  icon: auto-invert ${ICONS_URL}/custom/vuedotjs.svg
                  url: https://vuejs.org/guide/introduction.html
                - title: Vueuse
                  icon: auto-invert ${ICONS_URL}/custom/vueuse.svg
                  url: https://vueuse.org/guide/
                - title: Awesome Vue
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/vuejs/awesome-vue#readme

        - type: bookmarks
          title: Nuxt
          css-class: list-item-inline
          groups:
            - links:
                - title: Docs
                  url: https://nuxt.com/docs/getting-started/introduction
                - title: Modules
                  url: https://nuxt.com/modules
                - title: Guide
                  url: https://nuxt.com/docs/guide
                - title: API
                  url: https://nuxt.com/docs/api

        - <<: *github-releases
          repositories:
            - nuxt/nuxt
            - nuxt/devtools
            - nuxt/scripts
            - nuxt/ui
            - nitrojs/nitro
            - vuejs/pinia
            - vuejs/core
            - vueuse/vueuse
            - victorgarciaesgi/regle

    - size: full
      widgets:

        - type: split-column
          css-class: "gap-10"
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: nuxt/nuxt

            - <<: *github-repository
              repository: vuejs/core

            - <<: *github-repository
              repository: vueuse/vueuse

        - <<: *xeddit-waterfall
          title: reddit communities
          options:
            subreddit: nuxt+vuejs
            limit: 50
