- name: "Vue" # ðŸŸ¢
  slug: vue
  width: wide
  columns:

    - size: small
      widgets:

        - type: search
          search-engine: https://github.com/nuxt/nuxt/issues?q={QUERY}
          new-tab: true
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=nuxt+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/r/Nuxt/search?q={QUERY}&restrict_sr=on&sort=new&t=all
            - title: Github
              shortcut: "!g"
              url: https://github.com/nuxt/nuxt/issues?q={QUERY}

        - type: bookmarks
          groups:
            - hide-arrow: true
              links:
                - title: Vue.js
                  icon: auto-invert ${ICONS_URL}/custom/vuedotjs.svg
                  url: https://vuejs.org/guide/introduction.html
                - title: Vueuse
                  icon: auto-invert ${ICONS_URL}/custom/vueuse.svg
                  url: https://vueuse.org/guide/
                - title: Awesome Vue
                  icon: auto-invert ${ICONS_URL}/github-dark
                  url: https://github.com/vuejs/awesome-vue#readme

        - type: bookmarks
          title: Nuxt
          css-class: list-item-inline
          groups:
            - links:
                - title: Docs
                  url: https://nuxt.com/docs/getting-started/introduction
                - title: Modules
                  url: https://nuxt.com/modules
                - title: Guide
                  url: https://nuxt.com/docs/guide
                - title: API
                  url: https://nuxt.com/docs/api

        - <<: *github-releases
          repositories:
            - nuxt/nuxt
            - nuxt/devtools
            - nuxt/scripts
            - nuxt/ui
            - nitrojs/nitro
            - vuejs/pinia
            - vuejs/core
            - vueuse/vueuse
            - victorgarciaesgi/regle

    - size: full
      widgets:

        - type: split-column
          max-columns: 3
          widgets:

            - <<: *github-repository
              repository: nuxt/nuxt

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  title: Vue
                  subreddit: vuejs

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: vuejs

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: vuejs

            - <<: *backube-latest
              title: Videos
              options:
                collapse-after-rows: 8
              parameters:
                <<: *backube-video-parameters
                filter: channel.category.code="dev"&&(channel.tags.name?="vuejs"||channel.tags.name?="nuxtjs"||title~"vuejs"||title~"nuxtjs")

            - type: group
              widgets:

                - <<: *reddit-simple-full
                  title: Nuxt
                  subreddit: nuxt

                - <<: *reddit-simple-top-week
                  title: Top This Week
                  subreddit: nuxt

                - <<: *reddit-simple-top-month
                  title: Month
                  subreddit: nuxt
