- name: "#rift"
  slug: wr
  width: wide

  columns:

    - size: small
      widgets:

        - type: search
          search-engine: ${REDDIT_URL}/r/wildrift/search?q={QUERY}&restrict_sr=on&sort=new&t=all
          new-tab: true
          placeholder: Search in r/wildrift
          bangs:
            - title: YouTube
              shortcut: "!y"
              url: ${YOUTUBE_URL}/results?search_query=wildrift+{QUERY}
            - title: Reddit
              shortcut: "!r"
              url: ${REDDIT_URL}/search/?q={QUERY}

        - type: twitch-channels
          channels: ["itzstu4rt"]
          title: Streamers

        - type: bookmarks
          groups:
            - links:
                - title: Account Management
                  icon: auto-invert ${ICONS_URL}/custom/riotgames.svg
                  url: https://account.riotgames.com/account
            - title: Wild Rift
              color: 196 86 62
              links:
                - title: Updates
                  url: https://wildrift.leagueoflegends.com/en-us/news/game-updates
                - title: Events
                  url: https://support-wildrift.riotgames.com/hc/en-us/sections/360010851213-Current-Events
                - title: WR Fire
                  url: https://www.wildriftfire.com
                - title: WR Meta
                  url: https://wr-meta.com

        - <<: *twitch-category
          title: Twitch Wildrift Streams [EN, TR]
          options:
            collapse-after-rows: 4
          body:
            query: |
              query {
                game(id: "514858") {
                  streams(first: 30, options: { languages: ["EN", "TR"] }) {
                    edges {
                      node {
                        id
                        createdAt
                        previewImageURL(width: 440, height: 248)
                        type
                        viewersCount
                        broadcaster {
                          login
                          displayName
                          profileImageURL(width: 300)
                          broadcastSettings {
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }

    - size: full
      widgets:

        - <<: *backube-latest
          title: "Videos"
          options:
            collapse-after-rows: 1
          parameters:
            <<: *backube-video-parameters
            filter: kind="video"&&channel.tags?~"yl0tdahhhqzc0ai"


        - <<: *xeddit-waterfall
          title: r/wildrift
          css-class: "x-h-100vh"
          options:
            subreddit: wildrift
