- &kaiten-docker-glance
  type: custom-api
  cache: *no-cache
  #url: http://kaiten:3000/docker/glance
  url: ${KAITEN_URL}/docker/glance
  allow-insecure: true
  frameless: true
  hide-header: true
  template: | #html
    $include: glance.gohtml
