- &kaiten-docker-grouped
  type: custom-api
  cache: *no-cache
  #url: http://kaiten:3000/docker/grouped
  url: ${KAITEN_URL}/docker/grouped
  allow-insecure: true
  template: | #html
    $include: grouped.gohtml
