- &kaiten-docker-list
  type: custom-api
  cache: *no-cache
  #url: http://kaiten:3000/docker/list
  url: ${KAITEN_URL}/docker/list
  allow-insecure: true
  template: | #html
    $include: list.gohtml
