server:
  assets-path: /assets

branding:
  logo-text: â‹ˆ
  favicon-url: /assets/dev.ico
  app-name: "Dev"
  app-icon-url: /assets/dev.png

$include: /shared/index.yml

pages:
  - $include: pages/dash.yml
  - $include: pages/inbox.yml
  - $include: pages/videos.yml
  - $include: pages/selfhost.yml
  - $include: pages/homelab.yml
  - $include: pages/devops.yml
  - $include: pages/env.yml
  - $include: pages/javascript.yml
  - $include: pages/vue.yml
  - $include: pages/react.yml
  - $include: pages/svelte.yml
  - $include: pages/go.yml
  - $include: pages/frontend.yml
  - $include: pages/backend.yml
  - $include: pages/database.yml
  - $include: pages/security.yml
  - $include: pages/linux.yml
  - $include: pages/windows.yml
  - $include: pages/cms.yml
  - $include: pages/svc.yml
  #- $include: pages/hardware.yml
